name: segmentation_chest
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - torchvision>=0.5.0
  - pretrainedmodels==0.7.4
  - efficientnet-pytorch==0.7.1
  - segmentation-models-pytorch
  - timm==0.9.7
  - tqdm
  - pillow
  - six
  - openvino-dev[pytorch,onnx]
